server {
    listen 80;
    server_name portfolio.adjassaweb.fr www.portfolio.adjassaweb.fr;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;
}